### ISSUE TITLE
icons and toolbar too small

### ISSUE THREAD

**Issue by zwhitchcox** [GalliumOS/galliumos-samus#2] opened 2017-09-08 23:58 UTC
Hey, thank you so much for creating this! It's really great.

I was wondering, on my screen the icons are really small, and when I'm on the login screen, that is really tiny. Is there any way to make that bigger?

**Comment by zwhitchcox** [comment] 2017-09-08 23:59
[here's a picture of what I'm talking about](http://i.imgur.com/ho84kKi.png)

**Comment by reynhout** [comment] 2017-09-09 00:07
Some things don't scale properly. Xfce is not built for HiDPI unfortunately.

I'm not sure which icons you're talking about in the screenshot, but you might find some UI controls for the application itself (Chrome?). Or you can adjust the scaling and resolution system-wide to find a combination you prefer.

I'm going to close this issue since it's not a bug (and because issues should be disabled for this repository -- we keep them all in https://github.com/GalliumOS/galliumos-distro/issues), but you'll likely find a broader discussion on our Reddit sub: https://reddit.com/r/GalliumOS.

**Closed by reynhout** 2017-09-09 00:07 UTC
